### ISSUE TITLE
[BUG] Can't Run WebApp on Linux

### ISSUE THREAD

**Issue by xavierpuigf** [Unity-Technologies/UnityRenderStreaming#503]
**Describe the bug**
I am trying to run the WebApp on linux, following the instructions here: https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.2/manual/customize_webapp.html
While I have managed to run this on a MacOS, I cannot build the app on linux. Is there any limitation I should be aware of?

When I run npm install, I get:
```
[       ...........] | diffTrees: sill install generateActionsToTake



npm WARN acorn-jsx@5.0.2 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 805 packages in 10.085s

14 packages are looking for funding
  run `npm fund` for details

found 30 vulnerabilities (11 low, 6 moderate, 12 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

And on npm run, I get

```
npm WARN acorn-jsx@5.0.2 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 805 packages in 9.936s

14 packages are looking for funding
  run `npm fund` for details

found 30 vulnerabilities (11 low, 6 moderate, 12 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> webserver@3.0.0 start .../UnityRenderStreaming/WebApp
> node ./build/index.js

start as public mode
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (//WebApp/node_modules/express/lib/application.js:618:24)
    at new RenderStreaming (/WebApp/build/index.js:27:36)
    at Function.RenderStreaming.run (/WebApp/build/index.js:69:16)
    at Object.<anonymous> (//WebApp/build/index.js:87:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webserver@3.0.0 start: `node ./build/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webserver@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-06-20T20_04_27_186Z-debug.log
```

**Environment (please complete the following information):**
Ubuntu 18.04.5 LTS

**Comment by xavierpuigf** [comment]
Resolved: need to use a port larger than 1024 when running the node.js WebApp
