### ISSUE TITLE
[BUG]: Pico build crashes when using Vulkan

### ISSUE THREAD

**Issue by ChilledCosmonaut** [Unity-Technologies/UnityRenderStreaming#787]
### Package version

3.1.0-exp.3

### Environment

```markdown
* OS: Android
* Unity version: Unity 2021.2
* Graphics API: Vulkan
* Browser: Node.js
```

### Steps To Reproduce

1. Download the Pico SDK
2. Set build target to Android and switch to Android 26, ARMv8
3. Build the project
4. Project crashes instantly on start

### Current Behavior

The application just won't start. Only a black screen for a few seconds

### Expected Behavior

A working application

### Anything else?

So I debugged a bit and it seems that the Vulkan API kind does not like both packages simultaneously. Using only either of these the project works fine, yet using both simultaneously leads to this weird crash behaviour.

Note: When selecting OpenGLES3 everything works just fine

The stack trace I retrieved:

```
09-29 13:00:17.152 16173 16197 E AndroidRuntime: FATAL EXCEPTION: UnityMain
09-29 13:00:17.152 16173 16197 E AndroidRuntime: Process: com.DefaultCompany.TestStreaming, PID: 16173
09-29 13:00:17.152 16173 16197 E AndroidRuntime: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-29 13:00:17.152 16173 16197 E AndroidRuntime: Version '2021.2.0f1 (4bf1ec4b23c9)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
09-29 13:00:17.152 16173 16197 E AndroidRuntime: Build fingerprint: 'Pico/A7H10/PICOA7H10:10/4.6.3/1:user/test-keys'
09-29 13:00:17.152 16173 16197 E AndroidRuntime: Revision: '0'
09-29 13:00:17.152 16173 16197 E AndroidRuntime: ABI: 'arm64'
09-29 13:00:17.152 16173 16197 E AndroidRuntime: Timestamp: 2022-09-29 13:00:16+0200
09-29 13:00:17.152 16173 16197 E AndroidRuntime: pid: 16173, tid: 16197, name: UnityMain  >>> com.DefaultCompany.TestStreaming <<<
09-29 13:00:17.152 16173 16197 E AndroidRuntime: uid: 10089
09-29 13:00:17.152 16173 16197 E AndroidRuntime: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x64696f72646e61
09-29 13:00:17.152 16173 16197 E AndroidRuntime:     x0  0000000000000073  x1  000000000000004f  x2  0000000000000019  x3  000000000000001c
09-29 13:00:17.152 16173 16197 E AndroidRuntime:     x4  0000007896f11238  x5  0000007896f11238  x6  0000007830fbb400  x7  0000007832589800
09-29 13:00:17.152 16173 16197 E AndroidRuntime:     x8  0000000000000000  x9  0000000000000032  x10 0000007830f2a574  x11 0000000000000064
09-29 13:00:17.152 16173 16197 E AndroidRuntime:     x12 000000002d0191e8  x13 0000007832589924  x14 00000078325898c0  x15 0000000000000001
09-29 13:00:17.152 16173 16197 E AndroidRuntime:     x16 0000000000000001  x17 0000000000000001  x18 000000000000000d  x19 000000002d0191e8
09-29 13:00:17.152 16173 16197 E AndroidRuntime:     x20 000000783addb190  x21 000000783addb1b8  x22 0000007830f2a500  x23 0000000000000006
09-29 13:00:17.152 16173 16197 E AndroidRuntime:     x24 2e64696f72646e61  x25 0000007830f2a510  x26 0000000000000007  x27 0000007830f2cff0
09-29 13:00:17.152 16173 16197 E AndroidRuntime:     x28 0000007830f2a568  x29 000000783addb180
09-29 13:00:17.152 16173 16197 E AndroidRuntime:     sp  000000783adda8a0  lr  00000077574d1418  pc  00000077574d13fc
09-29 13:00:17.152 16173 16197 E AndroidRuntime:
09-29 13:00:17.152 16173 16197 E AndroidRuntime: backtrace:
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #00 pc 00000000000ef3fc  /vendor/lib64/hw/vulkan.kona.so (qglinternal::vkCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)+996) (BuildId: de2bd84dbc9f586cec6be83966919ff6)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #01 pc 0000000000019ae0  /system/lib64/libvulkan.so (BuildId: 65842988e4765175425fce60d32268b1)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #02 pc 0000000000011c68  /system/lib64/libvulkan.so (BuildId: 65842988e4765175425fce60d32268b1)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #03 pc 000000000013b038  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libwebrtc.so (unity::webrtc::Hook_vkCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)+460)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #04 pc 00000000005e0508  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #05 pc 00000000005de790  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #06 pc 00000000005e2e28  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #07 pc 000000000033ed84  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #08 pc 00000000005a471c  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #09 pc 00000000005a496c  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #10 pc 0000000000304cc4  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #11 pc 0000000000306d88  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #12 pc 0000000000307ac0  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #13 pc 000000000031c174  /data/app/com.DefaultCompany.TestStreaming-1M39MzQlkfayIBc9pynoRQ==/lib/arm64/libunity.so (BuildId: 4cdbce042e0ab2122aa17b6bc4f967c2f16ea6cb)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #14 pc 0000000000140350  /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #15 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #16 pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #17 pc 00000000002e304c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #18 pc 00000000002de2ac  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+892) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #19 pc 00000000005a356c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+424) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #20 pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #21 pc 00000000005a3fb4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1040) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #22 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #23 pc 00000000005a2d24  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1788) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #24 pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #25 pc 00000000005a1504  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1352) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #26 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #27 pc 00000000005a3fb4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1040) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #28 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #29 pc 00000000002b4360  /apex/com.android.runtime/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.16264273401899315888)+240) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #30 pc 00000000005927ac  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1032) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #31 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #32 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #33 pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #34 pc 00000000004b1178  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #35 pc 00000000004b228c  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416) (BuildId: dee3193f9a622bfe7030fb902efcac83)09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #36 pc 00000000004f300c  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176) (BuildId: dee3193f9a622bfe7030fb902efcac83)
09-29 13:00:17.152 16173 16197 E AndroidRuntime:       #37 pc 00000000000e6920  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: c9ad25a272415816d0f572c8a33665c2)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:       #38 pc 0000000000084bec  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: c9ad25a272415816d0f572c8a33665c2)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at vulkan.qglinternal::vkCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)(vkCreateInstance:996)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libvulkan.0x19ae0(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libvulkan.0x11c68(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libwebrtc.unity::webrtc::Hook_vkCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)(Hook_vkCreateInstance:460)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x5e0508(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x5de790(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x5e2e28(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x33ed84(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x5a471c(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x5a496c(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x304cc4(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x306d88(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x307ac0(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libunity.0x31c174(Native Method)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.art_quick_generic_jni_trampoline(art_quick_generic_jni_trampoline:144)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.art_quick_invoke_stub(art_quick_invoke_stub:548)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)(Invoke:244)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)(ArtInterpreterToCompiledCodeBridge:384)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)(DoCall<false, false>:892)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.MterpInvokeDirect(MterpInvokeDirect:424)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.mterp_op_invoke_direct(mterp_op_invoke_direct:20)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.MterpInvokeStatic(MterpInvokeStatic:1040)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.mterp_op_invoke_static(mterp_op_invoke_static:20)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.MterpInvokeInterface(MterpInvokeInterface:1788)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.mterp_op_invoke_interface(mterp_op_invoke_interface:20)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.MterpInvokeVirtual(MterpInvokeVirtual:1352)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.mterp_op_invoke_virtual(mterp_op_invoke_virtual:20)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.MterpInvokeStatic(MterpInvokeStatic:1040)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.mterp_op_invoke_static(mterp_op_invoke_static:20)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.16264273401899315888)(Execute:240)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.artQuickToInterpreterBridge(artQuickToInterpreterBridge:1032)
09-29 13:00:17.153 16173 16197 E AndroidRuntime:        at libart.art_quick_to_interpreter_bridge(art_quick_to_interpreter_bridge:88)
```

**Comment by karasusan** [comment]
@ChilledCosmonaut 
Is this same issue?
https://github.com/Unity-Technologies/com.unity.webrtc/issues/437

**Comment by karasusan** [comment]
@ChilledCosmonaut
Can you check it?

**Comment by ChilledCosmonaut** [comment]
It seems to be the same. I guess just reopened a bit too late for me 😅
